### PR TITLE
Modernize Bulma/Sass Integration: Refactored Codebase, Upgraded Dependencies, and Resolved Compatibility Issues

### PR DESCRIPTION
**Pull request by Hael616**
T+55.6
# Upgraded Bulma and Sass for Modernization and Compatibility: Refactoring and Dependency Updates

This PR modernizes the Rouge Network project's frontend styling by upgrading Bulma and Sass to their latest versions and refactoring the Sass codebase for improved maintainability. The upgrade process addressed compatibility issues with Bulma extensions (`bulma-calendar`, `bulma-switch`) and ensured seamless integration with the project's existing functionality.

## Key Objectives:

- ***Upgrade Bulma and Sass:***  The primary goal was to leverage the latest features, bug fixes, and performance improvements in the newest versions of Bulma and Sass.
- ***Modernize Sass Syntax:*** Replace deprecated `@import` statements with the `@use` and `@forward` modules to enhance code organization, modularity, and maintainability.
- ***Integrate Forks:*** Move the forked and updated bulma-calendar and bulma-switch repositories directly into the ticket-dapp project for better local development and control.

### Dependency Conflicts:

After upgrading Bulma and Sass in the main project, compatibility errors arose due to the extensions relying on older versions.
- ***Troubleshooting:*** Extensive research into Bulma, Sass, and the extension documentation was conducted to understand the dependencies and upgrade paths.
- ***Resolution:*** The project was recloned to ensure a clean starting point. Both bulma-calendar and bulma-switch were then forked and updated to use the latest Bulma version. Code adjustments were made within these extensions to ensure smooth integration.

**Sass Refactoring:**

- ***`@import` Replacement:*** All instances of @import were replaced with @use and @forward for a more modular - Sass structure.
- ***Namespaces:*** Namespaces were introduced to prevent variable and mixin collisions.
- ***Code Organization:*** The Sass codebase was reorganized to improve readability and maintainability.
Testing and Validation:

Thoroughly tested all application functionality to ensure compatibility with the updated styles and dependencies.
Manually inspected the UI to confirm consistent visual appearance and functionality.

## Benefits:

- ***Resolved Errors:*** Eliminated compatibility errors and ensured smooth project execution.
- ***Modernized Styling:*** The project now benefits from the latest Bulma features and improvements.
- ***Enhanced Maintainability:*** The Sass codebase is more organized, easier to understand, and follows best practices, facilitating future updates.

***Next Steps:***

***Style Refinements:*** Minor styling adjustments may be needed to align the updated UI with the project's design guidelines (to be coordinated with @clbrge).
***Additional Testing:*** Further comprehensive testing is recommended to ensure all edge cases are covered.
***Long-Term Maintenance:*** Regular updates and dependency reviews will be essential to prevent future compatibility issues.

### CODE REVIEW

**Review by clbrge — CHANGES_REQUESTED** [review]
Could you move the bulma calendar fork and bulma switch inside the ticket dapp. it's fine to keep also a fork in your own spacename

**Comment by Hael616** [comment]
Okay

**Comment by Hael616** [comment]
@clbrge also I noticed the "global" flag used in the AppContext component style tag was throwing some errors, so I removed and imported the styles in JavaScript, but for some reason the styles aren't correct, the colors in UI is off.

**Comment by clbrge** [comment]
> @clbrge also I noticed the "global" flag used in the AppContext component style tag was throwing some errors, so I removed and imported the styles in JavaScript, but for some reason the styles aren't correct, the colors in UI is off.

I let you search the reason why. I'm sure there a way to fix this

**Comment by clbrge** [comment]
@Hael616 tell me when it's ready to merge...

**Comment by Hael616** [comment]
> @Hael616 tell me when it's ready to merge...

Hi @clbrge i just refactored Bulma Sass modules, remove dark mode functionality to align with UI design, what's left is to make sure the overrides.scss styles are properly loaded

**Comment by Hael616** [comment]
> T+55.6
> 
> # Upgraded Bulma and Sass for Modernization and Compatibility: Refactoring and Dependency Updates
> This PR modernizes the Rouge Network project's frontend styling by upgrading Bulma and Sass to their latest versions and refactoring the Sass codebase for improved maintainability. The upgrade process addressed compatibility issues with Bulma extensions (`bulma-calendar`, `bulma-switch`) and ensured seamless integration with the project's existing functionality.
> 
> ## Key Objectives:
> * _**Upgrade Bulma and Sass:**_  The primary goal was to leverage the latest features, bug fixes, and performance improvements in the newest versions of Bulma and Sass.
> * _**Modernize Sass Syntax:**_ Replace deprecated `@import` statements with the `@use` and `@forward` modules to enhance code organization, modularity, and maintainability.
> * _**Integrate Forks:**_ Move the forked and updated bulma-calendar and bulma-switch repositories directly into the ticket-dapp project for better local development and control.
> 
> ## Challenges and Solutions:
> ### Dependency Conflicts:
> After upgrading Bulma and Sass in the main project, compatibility errors arose due to the extensions relying on older versions.
> 
> * _**Troubleshooting:**_ Extensive research into Bulma, Sass, and the extension documentation was conducted to understand the dependencies and upgrade paths.
> * _**Resolution:**_ The project was recloned to ensure a clean starting point. Both bulma-calendar and bulma-switch were then forked and updated to use the latest Bulma version. Code adjustments were made within these extensions to ensure smooth integration.
> 
> **Sass Refactoring:**
> 
> * _**`@import` Replacement:**_ All instances of @import were replaced with @use and @forward for a more modular - Sass structure.
> * _**Namespaces:**_ Namespaces were introduced to prevent variable and mixin collisions.
> * _**Code Organization:**_ The Sass codebase was reorganized to improve readability and maintainability.
>   Testing and Validation:
> 
> Thoroughly tested all application functionality to ensure compatibility with the updated styles and dependencies. Manually inspected the UI to confirm consistent visual appearance and functionality.
> 
> ## Benefits:
> * _**Resolved Errors:**_ Eliminated compatibility errors and ensured smooth project execution.
> * _**Modernized Styling:**_ The project now benefits from the latest Bulma features and improvements.
> * _**Enhanced Maintainability:**_ The Sass codebase is more organized, easier to understand, and follows best practices, facilitating future updates.
> 
> _**Next Steps:**_
> 
> _**Style Refinements:**_ Minor styling adjustments may be needed to align the updated UI with the project's design guidelines (to be coordinated with @clbrge). _**Additional Testing:**_ Further comprehensive testing is recommended to ensure all edge cases are covered. _**Long-Term Maintenance:**_ Regular updates and dependency reviews will be essential to prevent future compatibility issues.

14T+25

Refactored Bulma Sass modules, removed dark mode functionality to align with UI design, what's left is to make sure the overrides.scss styles are properly loaded

**Comment by Hael616** [comment]
> > T+55.6
> > # Upgraded Bulma and Sass for Modernization and Compatibility: Refactoring and Dependency Updates
> > This PR modernizes the Rouge Network project's frontend styling by upgrading Bulma and Sass to their latest versions and refactoring the Sass codebase for improved maintainability. The upgrade process addressed compatibility issues with Bulma extensions (`bulma-calendar`, `bulma-switch`) and ensured seamless integration with the project's existing functionality.
> > ## Key Objectives:
> > 
> > * _**Upgrade Bulma and Sass:**_  The primary goal was to leverage the latest features, bug fixes, and performance improvements in the newest versions of Bulma and Sass.
> > * _**Modernize Sass Syntax:**_ Replace deprecated `@import` statements with the `@use` and `@forward` modules to enhance code organization, modularity, and maintainability.
> > * _**Integrate Forks:**_ Move the forked and updated bulma-calendar and bulma-switch repositories directly into the ticket-dapp project for better local development and control.
> > 
> > ## Challenges and Solutions:
> > ### Dependency Conflicts:
> > After upgrading Bulma and Sass in the main project, compatibility errors arose due to the extensions relying on older versions.
> > 
> > * _**Troubleshooting:**_ Extensive research into Bulma, Sass, and the extension documentation was conducted to understand the dependencies and upgrade paths.
> > * _**Resolution:**_ The project was recloned to ensure a clean starting point. Both bulma-calendar and bulma-switch were then forked and updated to use the latest Bulma version. Code adjustments were made within these extensions to ensure smooth integration.
> > 
> > **Sass Refactoring:**
> > 
> > * _**`@import` Replacement:**_ All instances of @import were replaced with @use and @forward for a more modular - Sass structure.
> > * _**Namespaces:**_ Namespaces were introduced to prevent variable and mixin collisions.
> > * _**Code Organization:**_ The Sass codebase was reorganized to improve readability and maintainability.
> >   Testing and Validation:
> > 
> > Thoroughly tested all application functionality to ensure compatibility with the updated styles and dependencies. Manually inspected the UI to confirm consistent visual appearance and functionality.
> > ## Benefits:
> > 
> > * _**Resolved Errors:**_ Eliminated compatibility errors and ensured smooth project execution.
> > * _**Modernized Styling:**_ The project now benefits from the latest Bulma features and improvements.
> > * _**Enhanced Maintainability:**_ The Sass codebase is more organized, easier to understand, and follows best practices, facilitating future updates.
> > 
> > _**Next Steps:**_
> > _**Style Refinements:**_ Minor styling adjustments may be needed to align the updated UI with the project's design guidelines (to be coordinated with @clbrge). _**Additional Testing:**_ Further comprehensive testing is recommended to ensure all edge cases are covered. _**Long-Term Maintenance:**_ Regular updates and dependency reviews will be essential to prevent future compatibility issues.
> 
> 14T+25
> 
> Refactored Bulma Sass modules, removed dark mode functionality to align with UI design, what's left is to make sure the overrides.scss styles are properly loaded

19T+1.5

Made sure overrides are properly loaded

**Comment by Hael616** [comment]
> > > T+55.6
> > > # Upgraded Bulma and Sass for Modernization and Compatibility: Refactoring and Dependency Updates
> > > This PR modernizes the Rouge Network project's frontend styling by upgrading Bulma and Sass to their latest versions and refactoring the Sass codebase for improved maintainability. The upgrade process addressed compatibility issues with Bulma extensions (`bulma-calendar`, `bulma-switch`) and ensured seamless integration with the project's existing functionality.
> > > ## Key Objectives:
> > > 
> > > * _**Upgrade Bulma and Sass:**_  The primary goal was to leverage the latest features, bug fixes, and performance improvements in the newest versions of Bulma and Sass.
> > > * _**Modernize Sass Syntax:**_ Replace deprecated `@import` statements with the `@use` and `@forward` modules to enhance code organization, modularity, and maintainability.
> > > * _**Integrate Forks:**_ Move the forked and updated bulma-calendar and bulma-switch repositories directly into the ticket-dapp project for better local development and control.
> > > 
> > > ## Challenges and Solutions:
> > > ### Dependency Conflicts:
> > > After upgrading Bulma and Sass in the main project, compatibility errors arose due to the extensions relying on older versions.
> > > 
> > > * _**Troubleshooting:**_ Extensive research into Bulma, Sass, and the extension documentation was conducted to understand the dependencies and upgrade paths.
> > > * _**Resolution:**_ The project was recloned to ensure a clean starting point. Both bulma-calendar and bulma-switch were then forked and updated to use the latest Bulma version. Code adjustments were made within these extensions to ensure smooth integration.
> > > 
> > > **Sass Refactoring:**
> > > 
> > > * _**`@import` Replacement:**_ All instances of @import were replaced with @use and @forward for a more modular - Sass structure.
> > > * _**Namespaces:**_ Namespaces were introduced to prevent variable and mixin collisions.
> > > * _**Code Organization:**_ The Sass codebase was reorganized to improve readability and maintainability.
> > >   Testing and Validation:
> > > 
> > > Thoroughly tested all application functionality to ensure compatibility with the updated styles and dependencies. Manually inspected the UI to confirm consistent visual appearance and functionality.
> > > ## Benefits:
> > > 
> > > * _**Resolved Errors:**_ Eliminated compatibility errors and ensured smooth project execution.
> > > * _**Modernized Styling:**_ The project now benefits from the latest Bulma features and improvements.
> > > * _**Enhanced Maintainability:**_ The Sass codebase is more organized, easier to understand, and follows best practices, facilitating future updates.
> > > 
> > > _**Next Steps:**_
> > > _**Style Refinements:**_ Minor styling adjustments may be needed to align the updated UI with the project's design guidelines (to be coordinated with @clbrge). _**Additional Testing:**_ Further comprehensive testing is recommended to ensure all edge cases are covered. _**Long-Term Maintenance:**_ Regular updates and dependency reviews will be essential to prevent future compatibility issues.
> > 
> > 
> > 14T+25
> > Refactored Bulma Sass modules, removed dark mode functionality to align with UI design, what's left is to make sure the overrides.scss styles are properly loaded
> 
> 19T+1.5
> 
> Made sure overrides are properly loaded

T+1.5

Added dark mode to the app

**Comment by clbrge** [comment]
shoudn't we try to merge this? There is still one change marked are requested...

**Comment by Hael616** [comment]
> shoudn't we try to merge this? There is still one change marked are requested...

Yes we should

**Review by clbrge — APPROVED** [review]

**Pull request merged**
