### PR TITLE
Eoa integration

### PR DESCRIPTION
**Pull request by Hael616**
27T+15

Implemented basic signer with MagicSigner

### CODE REVIEW

**Comment by clbrge** [comment]
Does it need some changes in the config . after npm i , i got 
app.js:83 TypeError: Cannot read properties of undefined (reading 'request')
    at Object.transport (viem.js?v=5cd64508:2541:23)
    at createClient (viem.js?v=5cd64508:2341:49)
    at createWalletClient (viem.js?v=5cd64508:6662:18)
    at eoa-signer.js:5:16

**Comment by Hael616** [comment]
> Does it need some changes in the config . after npm i , i got 
> 
> app.js:83 TypeError: Cannot read properties of undefined (reading 'request')
> 
>     at Object.transport (viem.js?v=5cd64508:2541:23)
> 
>     at createClient (viem.js?v=5cd64508:2341:49)
> 
>     at createWalletClient (viem.js?v=5cd64508:6662:18)
> 
>     at eoa-signer.js:5:16

I'm on it

**Comment by Hael616** [comment]
> > Does it need some changes in the config . after npm i , i got
> > app.js:83 TypeError: Cannot read properties of undefined (reading 'request')
> > ```
> > at Object.transport (viem.js?v=5cd64508:2541:23)
> > 
> > at createClient (viem.js?v=5cd64508:2341:49)
> > 
> > at createWalletClient (viem.js?v=5cd64508:6662:18)
> > 
> > at eoa-signer.js:5:16
> > ```
> 
> I'm on it

Hi @clbrge i just removed the line causing the issue since its not required, i added two env variables namely:

VITE_ALCHEMY_API_KEY= from alchemy
VITE_MAGIC_SDK_API_KEY= from magic sdk

**Comment by clbrge** [comment]
Ok could you document a bit how to populate this new VARS. thxs

**Comment by Hael616** [comment]
> lchemy
> VITE_MAGIC_SDK_API_KEY= from magic sdk

[Alchemy API Key](https://dashboard.alchemy.com/apps)
[MagicSDK](https://dashboard.magic.link/login)

Also i noticed alchemy released 4.0.0.beta, and won't long term support for third party signers

**Review by clbrge — CHANGES_REQUESTED** [review]
1) Please rebase with main to remove conflicting files.
2) I have some errors with bulma:
Screenshot from 2024-08-31 11-37-37
3) be careful not to commit files like vite.config.js.timestamp-*

**Comment by Hael616** [comment]
Alright will do

**Comment by Hael616** [comment]
Hi @clbrge good morning, i just made the changes requested please review.

**Comment by clbrge** [comment]
I can enter the code but after the verifying step , the interface goes back to the unconnected state without any message on the console. What happens after you put the code for you?

**Comment by Hael616** [comment]
> I can enter the code but after the verifying step , the interface goes back to the unconnected state without any message on the console. What happens after you put the code for you?

Do you mean after you sign in as EOA, or web3 onboard

If yes, I don't know what to do with the signer returned by magic or how to integrate into the app that was why I came to you in the first place.

**Comment by clbrge** [comment]
Hum ok . I will merge that and try to follow up on this

**Comment by Hael616** [comment]
> Hum ok . I will merge that and try to follow up on this 

Okay, I'll check in for updates.

**Pull request merged**
